using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Sockets;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using WeatherImageGenerator.Models;
using WeatherImageGenerator.Utilities;

namespace WeatherImageGenerator.Services
{
    /// <summary>
    /// Lightweight MPEG-TS byte pipe that reads from Tunarr's HTTP stream and forwards
    /// raw 188-byte TS packets directly over TCP to connected clients.
    /// When an EAS alert is triggered, the pipe seamlessly splices a pre-encoded
    /// alert .ts segment into every active client stream, then resumes the Tunarr feed —
    /// maintaining continuity counters and monotonic PTS/DTS/PCR timestamps throughout.
    ///
    /// All channels share a single TCP listener port (the public Tunarr port, e.g. 8000).
    /// When a client connects with an HTTP GET, the request path determines which Tunarr
    /// channel to pipe (e.g. GET /stream/channels/{uuid}.ts). Raw TCP clients without an
    /// HTTP request are routed to the first configured channel.
    /// </summary>
    public class StreamPipeService
    {
        // ── Configuration ──────────────────────────────────────────────────
        private readonly StreamProxySettings _settings;
        private CancellationTokenSource? _cts;

        public bool IsRunning { get; private set; }

        // ── Per-channel state (keyed by ProxyChannelNumber) ────────────────
        private readonly ConcurrentDictionary<int, ChannelPipeState> _channels = new();

        // ── Channel lookup by TunarrChannelId (for HTTP path routing) ──────
        private readonly ConcurrentDictionary<string, ChannelPipeState> _channelsByTunarrId = new();

        // ── Single shared TCP listener ─────────────────────────────────────
        private TcpListener? _sharedListener;

        // ── Alert splice state (global — one alert at a time) ──────────────
        private volatile string? _activeAlertTsPath;
        private double _activeAlertDuration;
        private readonly object _alertDurationLock = new();
        private readonly ManualResetEventSlim _alertSignal = new(false);
        private int _alertGeneration; // incremented per alert to prevent stale-signal races

        // ── HLS alert injection state (segments generated by FFmpeg, served via HTTP proxy) ──
        private volatile string? _alertHlsDir;
        private volatile string? _alertHlsInjectionBlock;
        private long _alertHlsExpiryTicks; // DateTime.UtcNow.Ticks; use Interlocked for thread safety
        private const string AlertHlsSegmentPrefix = "eas_";

        // ── Regex to extract channel ID from HTTP request path ─────────────
        // Matches: /stream/channels/{id}.ts  or  /stream/{N}.ts  or just /{id}.ts
        private static readonly Regex ChannelPathRegex = new(
            @"/(?:stream/(?:channels/)?)?([^/]+?)(?:\.ts)?(?:\?.*)?$",
            RegexOptions.IgnoreCase | RegexOptions.Compiled);

        // ── Sentinel returned by HandleHttpHandshake when the request was an API
        //    proxy (already fully handled — caller should just close the connection).
        private const string API_PROXY_HANDLED = "\x00__API_PROXIED__";

        // ── Shared HttpClient for short-lived API proxy requests ───────────
        private static readonly HttpClient _apiProxyClient = new() { Timeout = TimeSpan.FromSeconds(30) };

        // ── Per-channel stream profiles (learned via ffprobe + PID parsing) ──
        private readonly ConcurrentDictionary<string, ChannelStreamProfile> _channelProfiles = new();

        // ────────────────────────────────────────────────────────────────────
        // Construction
        // ────────────────────────────────────────────────────────────────────

        public StreamPipeService(StreamProxySettings settings)
        {
            _settings = settings ?? throw new ArgumentNullException(nameof(settings));
        }

        // ────────────────────────────────────────────────────────────────────
        // Lifecycle
        // ────────────────────────────────────────────────────────────────────

        public void Start()
        {
            if (IsRunning) return;

            try
            {
                _cts = new CancellationTokenSource();

                if (_settings.Channels.Count == 0)
                {
                    Logger.Log("[StreamPipe] No channels configured — nothing to pipe.", Logger.LogLevel.Warning);
                    return;
                }

                // Register all channels (single shared listener — no per-channel ports)
                foreach (var ch in _settings.Channels)
                {
                    var state = new ChannelPipeState(ch, _settings.ListenPort);
                    _channels[ch.ProxyChannelNumber] = state;

                    // Index by TunarrChannelId for HTTP path-based routing
                    if (!string.IsNullOrEmpty(ch.TunarrChannelId))
                        _channelsByTunarrId[ch.TunarrChannelId] = state;
                }

                // Start single shared TCP listener on the public port
                _ = StartSharedListener(_cts.Token);

                IsRunning = true;

                string localIp = NetworkHelper.GetLocalIPAddress();
                Logger.Log($"[StreamPipe] ✓ MPEG-TS byte pipe started on port {_settings.ListenPort}", Logger.LogLevel.Info);
                Logger.Log($"[StreamPipe]   Tunarr upstream: {_settings.TunarrBaseUrl}", Logger.LogLevel.Info);
                foreach (var kv in _channels.OrderBy(k => k.Key))
                {
                    var s = kv.Value;
                    Logger.Log($"[StreamPipe]   Channel {s.Config.ProxyChannelNumber} ({s.Config.DisplayName}): http://{localIp}:{_settings.ListenPort}/stream/channels/{s.Config.TunarrChannelId}.ts  alert={s.Config.AlertInterruptEnabled}", Logger.LogLevel.Info);
                }
            }
            catch (Exception ex)
            {
                IsRunning = false;
                Logger.Log($"[StreamPipe] Failed to start: {ex.Message}", Logger.LogLevel.Error);
            }
        }

        public async Task StopAsync()
        {
            if (!IsRunning) return;

            try
            {
                _cts?.Cancel();

                try { _sharedListener?.Stop(); } catch { }

                foreach (var kv in _channels)
                    kv.Value.Dispose();
                _channels.Clear();
                _channelsByTunarrId.Clear();

                IsRunning = false;
                Logger.Log("[StreamPipe] Pipe stopped.", Logger.LogLevel.Info);
            }
            catch (Exception ex)
            {
                Logger.Log($"[StreamPipe] Error stopping: {ex.Message}", Logger.LogLevel.Warning);
            }

            await Task.CompletedTask;
        }

        // ────────────────────────────────────────────────────────────────────
        // Stream probing — learn upstream codec/resolution/fps via ffprobe
        // ────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Returns the best available stream profile across all alert-enabled channels,
        /// or null if no channels have been probed yet.
        /// </summary>
        public ChannelStreamProfile? GetBestStreamProfile()
        {
            return _channelProfiles.Values
                .Where(p => p.IsComplete)
                .OrderByDescending(p => p.LastProbed)
                .FirstOrDefault();
        }

        /// <summary>
        /// Probes a Tunarr channel's live stream via ffprobe to discover codec parameters.
        /// Merges result with PID data already learned from UpstreamPidMap.
        /// </summary>
        private async Task ProbeChannelStreamAsync(ProxyChannelConfig chConfig, UpstreamPidMap pidMap)
        {
            string channelId = chConfig.TunarrChannelId;

            // Skip if recently probed (within 1 hour)
            if (_channelProfiles.TryGetValue(channelId, out var existing) &&
                existing.IsComplete &&
                (DateTime.UtcNow - existing.LastProbed).TotalHours < 1)
            {
                // Just refresh PIDs from the live map in case they shifted
                if (pidMap.IsLearned)
                {
                    existing.PmtPid = pidMap.PmtPid;
                    existing.PcrPid = pidMap.PcrPid;
                    existing.VideoPid = pidMap.VideoPid;
                    existing.AudioPid = pidMap.AudioPid;
                }
                return;
            }

            string probeUrl = $"{_settings.TunarrBaseUrl.TrimEnd('/')}/stream/channels/{channelId}.ts";

            try
            {
                Logger.Log($"[StreamPipe] Probing channel {chConfig.ProxyChannelNumber} ({chConfig.DisplayName}) via ffprobe...", Logger.LogLevel.Debug);

                var startInfo = new ProcessStartInfo
                {
                    FileName = "ffprobe",
                    Arguments = $"-v quiet -print_format json -show_streams -show_programs -read_intervals \"%+3\" \"{probeUrl}\"",
                    UseShellExecute = false,
                    CreateNoWindow = true,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true
                };

                using var process = Process.Start(startInfo);
                if (process == null)
                {
                    Logger.Log("[StreamPipe] Failed to start ffprobe.", Logger.LogLevel.Warning);
                    return;
                }

                var stdoutTask = process.StandardOutput.ReadToEndAsync();
                var stderrTask = process.StandardError.ReadToEndAsync();
                bool exited = process.WaitForExit(15000);

                if (!exited)
                {
                    try { process.Kill(); } catch { }
                    Logger.Log("[StreamPipe] ffprobe timed out.", Logger.LogLevel.Warning);
                    return;
                }

                string json = await stdoutTask;
                if (string.IsNullOrWhiteSpace(json))
                {
                    Logger.Log("[StreamPipe] ffprobe returned empty output.", Logger.LogLevel.Warning);
                    return;
                }

                var profile = ParseFfprobeJson(json);
                if (profile == null)
                {
                    Logger.Log("[StreamPipe] Failed to parse ffprobe output.", Logger.LogLevel.Warning);
                    return;
                }

                // Merge PID data from the live UpstreamPidMap
                if (pidMap.IsLearned)
                {
                    profile.PmtPid = pidMap.PmtPid;
                    profile.PcrPid = pidMap.PcrPid;
                    profile.VideoPid = pidMap.VideoPid;
                    profile.AudioPid = pidMap.AudioPid;
                }

                profile.LastProbed = DateTime.UtcNow;
                _channelProfiles[channelId] = profile;

                Logger.Log($"[StreamPipe] ✓ Channel {chConfig.ProxyChannelNumber} probed: {profile.Width}x{profile.Height} " +
                           $"{profile.FrameRate}fps {profile.VideoCodec} profile={profile.VideoProfile} level={profile.VideoLevel} " +
                           $"bitrate={profile.VideoBitrateBps / 1000}kbps PIDs: V={profile.VideoPid} A={profile.AudioPid} PMT={profile.PmtPid}",
                           Logger.LogLevel.Info);
            }
            catch (Exception ex)
            {
                Logger.Log($"[StreamPipe] ffprobe failed for channel {chConfig.ProxyChannelNumber}: {ex.Message}", Logger.LogLevel.Warning);
            }
        }

        /// <summary>
        /// Parses ffprobe JSON output into a ChannelStreamProfile.
        /// </summary>
        private static ChannelStreamProfile? ParseFfprobeJson(string json)
        {
            try
            {
                using var doc = System.Text.Json.JsonDocument.Parse(json);
                var root = doc.RootElement;

                if (!root.TryGetProperty("streams", out var streams))
                    return null;

                var profile = new ChannelStreamProfile();

                foreach (var stream in streams.EnumerateArray())
                {
                    string codecType = stream.TryGetProperty("codec_type", out var ct) ? ct.GetString() ?? "" : "";

                    if (codecType == "video")
                    {
                        profile.VideoCodec = stream.TryGetProperty("codec_name", out var cn) ? cn.GetString() ?? "h264" : "h264";
                        profile.Width = stream.TryGetProperty("width", out var w) ? w.GetInt32() : 0;
                        profile.Height = stream.TryGetProperty("height", out var h) ? h.GetInt32() : 0;
                        profile.VideoProfile = stream.TryGetProperty("profile", out var pr) ? pr.GetString() : null;
                        profile.VideoLevel = stream.TryGetProperty("level", out var lv) ? lv.GetInt32().ToString() : null;

                        // Parse frame rate from r_frame_rate (e.g. "24/1", "30000/1001")
                        if (stream.TryGetProperty("r_frame_rate", out var rfr))
                            profile.FrameRate = rfr.GetString() ?? "24/1";

                        // Bitrate
                        if (stream.TryGetProperty("bit_rate", out var br) && br.ValueKind == System.Text.Json.JsonValueKind.String)
                        {
                            if (int.TryParse(br.GetString(), out int bps))
                                profile.VideoBitrateBps = bps;
                        }

                        // Service ID from programs
                        if (root.TryGetProperty("programs", out var programs))
                        {
                            foreach (var prog in programs.EnumerateArray())
                            {
                                if (prog.TryGetProperty("program_id", out var pid))
                                {
                                    profile.ServiceId = pid.GetInt32();
                                    break;
                                }
                            }
                        }
                    }
                    else if (codecType == "audio")
                    {
                        profile.AudioCodec = stream.TryGetProperty("codec_name", out var cn) ? cn.GetString() ?? "aac" : "aac";
                        profile.AudioSampleRate = stream.TryGetProperty("sample_rate", out var sr) && sr.ValueKind == System.Text.Json.JsonValueKind.String
                            ? (int.TryParse(sr.GetString(), out int rate) ? rate : 48000) : 48000;
                        profile.AudioChannels = stream.TryGetProperty("channels", out var ch) ? ch.GetInt32() : 2;
                    }
                }

                return profile.Width > 0 && profile.Height > 0 ? profile : null;
            }
            catch (Exception ex)
            {
                Logger.Log($"[StreamPipe] ffprobe JSON parse error: {ex.Message}", Logger.LogLevel.Warning);
                return null;
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // Alert splice trigger (called from MainForm)
        // ────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Triggers an EAS alert splice on all alert-enabled channels.
        /// </summary>
        public void TriggerAlertSplice(string alertTsPath, double durationSeconds)
        {
            if (!IsRunning)
            {
                Logger.Log("[StreamPipe] Cannot trigger alert splice — pipe is not running.", Logger.LogLevel.Warning);
                return;
            }
            if (string.IsNullOrEmpty(alertTsPath) || !File.Exists(alertTsPath))
            {
                Logger.Log($"[StreamPipe] Cannot trigger alert splice — file missing: '{alertTsPath}'", Logger.LogLevel.Warning);
                return;
            }

            int totalClients = _channels.Values.Sum(c => c.ClientCount);
            Logger.Log($"[StreamPipe] 🚨 EAS ALERT SPLICE triggered — {Path.GetFileName(alertTsPath)} ({durationSeconds:F1}s), {totalClients} client(s) connected", Logger.LogLevel.Info);

            if (totalClients == 0)
            {
                Logger.Log("[StreamPipe] ⚠ WARNING: No clients are currently connected. The splice will have no visible effect.", Logger.LogLevel.Warning);
            }

            _activeAlertTsPath = alertTsPath;
            lock (_alertDurationLock) { _activeAlertDuration = durationSeconds; }
            Interlocked.Increment(ref _alertGeneration);
            _alertSignal.Set();

            // Also prepare HLS alert segments in background for clients consuming
            // Tunarr's HLS endpoint through this proxy. HLS latency is already
            // ~12-40s so the 1-2s FFmpeg segmentation is negligible.
            _ = PrepareAlertHlsSegmentsAsync(alertTsPath, durationSeconds);
        }

        // ────────────────────────────────────────────────────────────────────
        // Single shared TCP listener
        // ────────────────────────────────────────────────────────────────────

        private async Task StartSharedListener(CancellationToken ct)
        {
            _sharedListener = new TcpListener(
                _settings.AllowRemoteAccess ? IPAddress.Any : IPAddress.Loopback,
                _settings.ListenPort);

            try
            {
                _sharedListener.Start();
                Logger.Log($"[StreamPipe] Listening on port {_settings.ListenPort} (all channels)", Logger.LogLevel.Debug);

                while (!ct.IsCancellationRequested)
                {
                    TcpClient client;
                    try
                    {
                        client = await _sharedListener.AcceptTcpClientAsync(ct);
                    }
                    catch (OperationCanceledException) { break; }
                    catch (ObjectDisposedException) { break; }
                    catch (SocketException) { break; }

                    // Route and handle each client in its own task
                    _ = Task.Run(() => RouteAndHandleClient(client, ct), ct);
                }
            }
            catch (SocketException ex)
            {
                Logger.Log($"[StreamPipe] Listener failed on port {_settings.ListenPort}: {ex.Message}", Logger.LogLevel.Error);
            }
            catch (Exception ex) when (!ct.IsCancellationRequested)
            {
                Logger.Log($"[StreamPipe] Listener error: {ex.Message}", Logger.LogLevel.Error);
            }
            finally
            {
                try { _sharedListener?.Stop(); } catch { }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // Client routing (parses HTTP path → channel)
        // ────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Accepts a new TCP connection, reads the HTTP request (if any) to determine
        /// which channel the client wants, then routes to the correct channel pipe.
        /// </summary>
        private async Task RouteAndHandleClient(TcpClient tcpClient, CancellationToken ct)
        {
            var clientId = Guid.NewGuid().ToString("N")[..8];
            ChannelPipeState? channelState = null;

            try
            {
                tcpClient.NoDelay = true;
                tcpClient.SendBufferSize = 65536;
                tcpClient.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.KeepAlive, true);

                using var clientStream = tcpClient.GetStream();

                // Read HTTP request and extract channel ID from path.
                // Also sends the HTTP 200 response if it's an HTTP client.
                // Non-stream (API) requests are transparently proxied to Tunarr.
                string? resolvedChannelId = await HandleHttpHandshake(clientStream, ct);

                // If the request was already handled as an API proxy, we're done
                if (resolvedChannelId == API_PROXY_HANDLED)
                    return;

                // Resolve channel: try by TunarrChannelId first, then by channel number
                channelState = ResolveChannel(resolvedChannelId);

                if (channelState == null)
                {
                    Logger.Log($"[StreamPipe] Client {clientId}: could not resolve channel from request (path id='{resolvedChannelId ?? "null"}') — rejecting", Logger.LogLevel.Warning);
                    return;
                }

                channelState.IncrementClients();

                Logger.Log($"[StreamPipe] Client {clientId} connected to channel {channelState.Config.ProxyChannelNumber} ({channelState.Config.DisplayName})", Logger.LogLevel.Info);

                await PipeStreamLoop(channelState.Config, channelState, clientStream, clientId, ct);
            }
            catch (Exception ex) when (ex is IOException || ex is SocketException || ex is ObjectDisposedException)
            {
                // Client disconnected — normal
            }
            catch (OperationCanceledException) { }
            catch (Exception ex)
            {
                Logger.Log($"[StreamPipe] Client {clientId} error: {ex.Message}", Logger.LogLevel.Debug);
            }
            finally
            {
                if (channelState != null)
                {
                    Logger.Log($"[StreamPipe] Client {clientId} disconnected from channel {channelState.Config.ProxyChannelNumber}", Logger.LogLevel.Info);
                    channelState.DecrementClients();
                }
                try { tcpClient.Close(); } catch { }
            }
        }

        /// <summary>
        /// Resolves a channel ID string to a ChannelPipeState.
        /// Tries: exact TunarrChannelId match → case-insensitive → channel number → fallback.
        /// </summary>
        private ChannelPipeState? ResolveChannel(string? channelId)
        {
            if (string.IsNullOrEmpty(channelId))
            {
                // No HTTP path or raw TCP client — fall back to first channel
                return _channels.Values.FirstOrDefault();
            }

            // Try exact TunarrChannelId match (UUID)
            if (_channelsByTunarrId.TryGetValue(channelId, out var byId))
                return byId;

            // Try case-insensitive TunarrChannelId match
            var caseInsensitive = _channelsByTunarrId
                .FirstOrDefault(kv => string.Equals(kv.Key, channelId, StringComparison.OrdinalIgnoreCase));
            if (caseInsensitive.Value != null)
                return caseInsensitive.Value;

            // Try parsing as a channel number
            if (int.TryParse(channelId, out int chNum) && _channels.TryGetValue(chNum, out var byNum))
                return byNum;

            // No match — fall back to first channel
            Logger.Log($"[StreamPipe] Channel ID '{channelId}' not found — falling back to first channel", Logger.LogLevel.Warning);
            return _channels.Values.FirstOrDefault();
        }

        /// <summary>
        /// Returns true if the HTTP request path is a stream path that should be
        /// handled by the pipe. All other paths are proxied transparently to Tunarr.
        /// </summary>
        private static bool IsStreamPath(string path)
        {
            return path.StartsWith("/stream/", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Reads the HTTP request from the client (if present), sends an HTTP 200 response,
        /// and extracts the channel ID from the request path.
        /// Non-stream paths (API requests such as /api/xmltv.xml, /api/channels.m3u,
        /// HDHR discovery, etc.) are transparently proxied to Tunarr's internal port.
        /// Returns the extracted channel ID string, null if no HTTP request was sent,
        /// or API_PROXY_HANDLED if the request was already proxied to Tunarr.
        /// </summary>
        private async Task<string?> HandleHttpHandshake(NetworkStream stream, CancellationToken ct)
        {
            stream.ReadTimeout = 500; // ms
            string? channelId = null;

            try
            {
                if (!stream.DataAvailable)
                    await Task.Delay(200, ct); // give client time to send headers

                if (stream.DataAvailable)
                {
                    var peekBuf = new byte[4096];
                    int bytesRead = await stream.ReadAsync(peekBuf, 0, peekBuf.Length, ct);

                    if (bytesRead >= 4)
                    {
                        string header = System.Text.Encoding.ASCII.GetString(peekBuf, 0, Math.Min(bytesRead, 512));

                        if (header.StartsWith("GET ", StringComparison.OrdinalIgnoreCase))
                        {
                            // Extract request path: "GET /stream/channels/{id}.ts HTTP/1.1\r\n..."
                            int pathStart = 4; // after "GET "
                            int pathEnd = header.IndexOf(' ', pathStart);
                            if (pathEnd < 0) pathEnd = header.IndexOf('\r', pathStart);
                            if (pathEnd < 0) pathEnd = header.Length;

                            string requestPath = header.Substring(pathStart, pathEnd - pathStart);

                            // ── Alert HLS segment request → serve from local cache ──
                            // Must be checked BEFORE stream/API routing because alert
                            // segment URLs resolve relative to the playlist path and
                            // may appear under /stream/channels/*/eas_*.ts
                            string reqFileName = requestPath.Substring(requestPath.LastIndexOf('/') + 1).Split('?')[0];
                            if (reqFileName.StartsWith(AlertHlsSegmentPrefix, StringComparison.OrdinalIgnoreCase)
                                && reqFileName.EndsWith(".ts", StringComparison.OrdinalIgnoreCase))
                            {
                                stream.ReadTimeout = Timeout.Infinite;
                                await ServeAlertHlsSegment(stream, reqFileName, ct);
                                return API_PROXY_HANDLED;
                            }

                            // ── Non-stream request → proxy to Tunarr's internal port ──
                            if (!IsStreamPath(requestPath))
                            {
                                stream.ReadTimeout = Timeout.Infinite;
                                await ProxyApiRequestToTunarr(stream, requestPath, ct);
                                return API_PROXY_HANDLED;
                            }

                            // ── HLS request (.m3u8 playlist or /hls/ segment) → proxy with alert injection ──
                            if (IsHlsPath(requestPath))
                            {
                                stream.ReadTimeout = Timeout.Infinite;
                                await HandleHlsRequest(stream, requestPath, ct);
                                return API_PROXY_HANDLED;
                            }

                            // ── MPEG-TS stream request → extract channel ID ──
                            var match = ChannelPathRegex.Match(requestPath);
                            if (match.Success)
                            {
                                channelId = match.Groups[1].Value;
                            }

                            Logger.Log($"[StreamPipe] HTTP request: GET {requestPath} → channel id='{channelId ?? "?"}'", Logger.LogLevel.Debug);

                            // Send HTTP 200 response for MPEG-TS stream
                            string httpResponse =
                                "HTTP/1.1 200 OK\r\n" +
                                "Content-Type: video/mp2t\r\n" +
                                "Connection: keep-alive\r\n" +
                                "Cache-Control: no-cache, no-store\r\n" +
                                "Access-Control-Allow-Origin: *\r\n" +
                                "\r\n";
                            var respBytes = System.Text.Encoding.ASCII.GetBytes(httpResponse);
                            await stream.WriteAsync(respBytes, 0, respBytes.Length, ct);
                            await stream.FlushAsync(ct);
                        }
                        // If it wasn't HTTP, these bytes are lost — but raw TCP MPEG-TS
                        // clients don't send anything before receiving.
                    }
                }
            }
            catch (IOException) { } // timeout — no data sent, client is raw TCP
            catch (OperationCanceledException) { }
            finally
            {
                stream.ReadTimeout = Timeout.Infinite; // restore for streaming
            }

            return channelId;
        }

        /// <summary>
        /// Forwards a non-stream HTTP GET request to Tunarr's internal port and writes
        /// the complete HTTP response (status line + headers + body) back to the client.
        /// This allows API endpoints like /api/xmltv.xml, /api/channels.m3u, HDHR
        /// discovery (/discover.json, /lineup.json, etc.) to work transparently through
        /// the proxy.
        /// </summary>
        private async Task ProxyApiRequestToTunarr(NetworkStream clientStream, string requestPath, CancellationToken ct)
        {
            try
            {
                string tunarrUrl = $"{_settings.TunarrBaseUrl.TrimEnd('/')}{requestPath}";
                Logger.Log($"[StreamPipe] API proxy: GET {requestPath} → {tunarrUrl}", Logger.LogLevel.Debug);

                using var response = await _apiProxyClient.GetAsync(tunarrUrl, ct);

                // Build the raw HTTP response to send back to the client
                var sb = new StringBuilder();
                sb.Append($"HTTP/1.1 {(int)response.StatusCode} {response.ReasonPhrase}\r\n");

                // Forward response headers
                foreach (var h in response.Headers)
                    foreach (var v in h.Value)
                        sb.Append($"{h.Key}: {v}\r\n");
                foreach (var h in response.Content.Headers)
                    foreach (var v in h.Value)
                        sb.Append($"{h.Key}: {v}\r\n");

                sb.Append("Access-Control-Allow-Origin: *\r\n");
                sb.Append("Connection: close\r\n");
                sb.Append("\r\n");

                var headerBytes = Encoding.ASCII.GetBytes(sb.ToString());
                await clientStream.WriteAsync(headerBytes, 0, headerBytes.Length, ct);

                // Forward the body
                var body = await response.Content.ReadAsByteArrayAsync(ct);
                if (body.Length > 0)
                {
                    await clientStream.WriteAsync(body, 0, body.Length, ct);
                }

                await clientStream.FlushAsync(ct);
                Logger.Log($"[StreamPipe] API proxy: {requestPath} → {(int)response.StatusCode} ({body.Length} bytes)", Logger.LogLevel.Debug);
            }
            catch (Exception ex)
            {
                Logger.Log($"[StreamPipe] API proxy error for {requestPath}: {ex.Message}", Logger.LogLevel.Warning);

                // Try to send a 502 Bad Gateway response
                try
                {
                    string errResponse = "HTTP/1.1 502 Bad Gateway\r\nConnection: close\r\nContent-Length: 0\r\n\r\n";
                    var errBytes = Encoding.ASCII.GetBytes(errResponse);
                    await clientStream.WriteAsync(errBytes, 0, errBytes.Length, ct);
                    await clientStream.FlushAsync(ct);
                }
                catch { }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // Main pipe loop — reads from Tunarr, writes to client, splices alerts
        // ────────────────────────────────────────────────────────────────────

        private async Task PipeStreamLoop(
            ProxyChannelConfig chConfig,
            ChannelPipeState channelState,
            Stream clientStream,
            string clientId,
            CancellationToken ct)
        {
            string tunarrUrl = $"{_settings.TunarrBaseUrl.TrimEnd('/')}/stream/channels/{chConfig.TunarrChannelId}.ts";

            using var httpClient = new HttpClient { Timeout = Timeout.InfiniteTimeSpan };

            // ── Per-client stream state ────────────────────────────────
            var ccTracker = new ConcurrentDictionary<int, int>(); // PID → last CC sent
            long lastPcrSeen = 0;
            long lastPtsSeen = 0;

            // ── Upstream PID map (learned from PAT/PMT) for splice PID remapping ──
            var upstreamPidMap = new UpstreamPidMap();
            bool probeTriggered = false; // fire-once: trigger ffprobe after PIDs learned

            // ── Discontinuity tracking: after an alert splice, the first N packets
            //    from Tunarr get the discontinuity_indicator set so clients re-lock ──
            int discontinuityRemaining = 0;

            int consecutiveFailures = 0;
            int maxRetries = Math.Max(_settings.MaxReconnectRetries, 1);
            int reconnectBaseMs = Math.Max(_settings.ReconnectBaseMs, 500);

            while (!ct.IsCancellationRequested)
            {
                // ── Phase 1: Connect to Tunarr upstream ────────────────
                try
                {
                    Logger.Log($"[StreamPipe] {clientId}: Connecting to Tunarr ({tunarrUrl})", Logger.LogLevel.Debug);

                    using var response = await httpClient.GetAsync(tunarrUrl, HttpCompletionOption.ResponseHeadersRead, ct);
                    response.EnsureSuccessStatusCode();

                    using var upstream = await response.Content.ReadAsStreamAsync(ct);

                    consecutiveFailures = 0; // connected successfully

                    var buffer = new byte[MpegTsHelper.PacketSize * 49]; // ~9KB per read
                    var leftover = new byte[MpegTsHelper.PacketSize];
                    int leftoverLen = 0;
                    var preallocWorkBuf = new byte[leftover.Length + buffer.Length]; // reusable work buffer

                    // Track which alert generation this client has already spliced
                    int lastSplicedGeneration = _alertGeneration;

                    // ── Phase 2: Forward Tunarr stream ─────────────────
                    while (!ct.IsCancellationRequested)
                    {
                        // ── Check for alert trigger ────────────────────
                        if (chConfig.AlertInterruptEnabled && _alertSignal.IsSet && _activeAlertTsPath != null)
                        {
                            int currentGen = _alertGeneration;
                            if (currentGen != lastSplicedGeneration)
                            {
                                string alertPath = _activeAlertTsPath;
                                double alertDur;
                                lock (_alertDurationLock) { alertDur = _activeAlertDuration; }

                                if (alertPath != null && File.Exists(alertPath))
                                {
                                    Logger.Log($"[StreamPipe] {clientId}: 🚨 Alert detected — splicing {Path.GetFileName(alertPath)} ({alertDur:F1}s)", Logger.LogLevel.Info);

                                    try
                                    {
                                        var spliceResult = await SpliceAlertTs(alertPath, clientStream, clientId, alertDur, ct, upstreamPidMap, ccTracker);

                                        // Mark this generation as spliced so we don't re-splice
                                        // the same alert in a tight loop
                                        lastSplicedGeneration = currentGen;

                                        Logger.Log($"[StreamPipe] {clientId}: ✓ Alert splice complete — {spliceResult.ElapsedSeconds:F1}s paced write — resuming Tunarr stream", Logger.LogLevel.Info);
                                    }
                                    catch (Exception spliceEx) when (spliceEx is IOException || spliceEx is SocketException)
                                    {
                                        // Client disconnected during splice — propagate so outer handler exits cleanly
                                        Logger.Log($"[StreamPipe] {clientId}: Alert splice failed (client disconnected): {spliceEx.Message}", Logger.LogLevel.Warning);
                                        throw;
                                    }

                                    // After the splice the stream switches back to
                                    // Tunarr's program. If this was a hard splice (no PID match),
                                    // mark packets with discontinuity so clients re-lock.
                                    // For soft splice (PIDs matched), CC is already continuous
                                    // so only a small burst is needed as safety net.
                                    if (!upstreamPidMap.IsLearned)
                                    {
                                        ccTracker.Clear();
                                        discontinuityRemaining = 200;
                                    }
                                    else
                                    {
                                        // Soft splice: small safety burst (decoder should already be in sync)
                                        discontinuityRemaining = 20;
                                    }

                                    continue; // resume inner loop — read from upstream
                                }
                            }
                        }

                        int bytesRead = await upstream.ReadAsync(buffer, 0, buffer.Length, ct);

                        if (bytesRead == 0)
                        {
                            // Upstream closed gracefully — send null packets to keep client alive
                            Logger.Log($"[StreamPipe] {clientId}: Upstream closed gracefully. Reconnecting in 2s...", Logger.LogLevel.Warning);
                            try
                            {
                                var nullPkt = MpegTsHelper.CreateNullPacket();
                                for (int i = 0; i < 50; i++)
                                    await clientStream.WriteAsync(nullPkt, 0, nullPkt.Length, ct);
                                await clientStream.FlushAsync(ct);
                            }
                            catch { break; } // client gone

                            await Task.Delay(2000, ct);
                            break; // break inner loop to reconnect upstream
                        }

                        // ── Packet-aligned processing (zero-alloc) ────
                        byte[] workBuf;
                        int workLen;
                        if (leftoverLen > 0)
                        {
                            Buffer.BlockCopy(leftover, 0, preallocWorkBuf, 0, leftoverLen);
                            Buffer.BlockCopy(buffer, 0, preallocWorkBuf, leftoverLen, bytesRead);
                            workBuf = preallocWorkBuf;
                            workLen = leftoverLen + bytesRead;
                            leftoverLen = 0;
                        }
                        else
                        {
                            workBuf = buffer;
                            workLen = bytesRead;
                        }

                        int syncOff = MpegTsHelper.FindSyncOffset(workBuf, 0, workLen);
                        if (syncOff < 0)
                            continue; // no valid sync — discard and read more

                        int pos = syncOff;
                        while (pos + MpegTsHelper.PacketSize <= workLen)
                        {
                            if (workBuf[pos] != MpegTsHelper.SyncByte)
                            {
                                int nextSync = MpegTsHelper.FindSyncOffset(workBuf, pos, workLen - pos);
                                if (nextSync < 0) break;
                                pos = nextSync;
                                continue;
                            }

                            // ── Post-splice discontinuity: mark first N Tunarr packets ──
                            // This tells the client's decoder to re-lock on the
                            // stream's PAT/PMT and reset CC / timestamp tracking.
                            if (discontinuityRemaining > 0)
                            {
                                MpegTsHelper.SetDiscontinuityIndicator(workBuf, pos);
                                discontinuityRemaining--;
                            }

                            // Track timestamps (read-only — never rewrite Tunarr data)
                            if (MpegTsHelper.HasPcr(workBuf, pos))
                            {
                                long pcr = MpegTsHelper.GetPcrBase(workBuf, pos);
                                if (pcr >= 0) lastPcrSeen = pcr;
                            }

                            long pts = MpegTsHelper.GetPts(workBuf, pos);
                            if (pts >= 0)
                                lastPtsSeen = pts;

                            // Track CC for diagnostic purposes (read-only)
                            {
                                int pid = MpegTsHelper.GetPid(workBuf, pos);
                                if (MpegTsHelper.HasPayload(workBuf, pos))
                                    ccTracker[pid] = MpegTsHelper.GetContinuityCounter(workBuf, pos);
                            }

                            // ── Learn upstream PID structure from PAT/PMT ──
                            upstreamPidMap.LearnFromPacket(workBuf, pos);

                            // ── Trigger background probe once PIDs are learned ──
                            if (!probeTriggered && upstreamPidMap.IsLearned)
                            {
                                probeTriggered = true;
                                _ = ProbeChannelStreamAsync(chConfig, upstreamPidMap);
                            }

                            pos += MpegTsHelper.PacketSize;
                        }

                        // Save leftover bytes
                        if (pos < workLen)
                        {
                            leftoverLen = workLen - pos;
                            Buffer.BlockCopy(workBuf, pos, leftover, 0, leftoverLen);
                        }

                        // Write processed packets to client (NoDelay=true pushes immediately)
                        int writeStart = syncOff;
                        int writeLen = pos - syncOff;
                        if (writeLen > 0)
                        {
                            await clientStream.WriteAsync(workBuf, writeStart, writeLen, ct);
                        }
                    }
                }
                catch (Exception ex) when (ex is IOException || ex is SocketException)
                {
                    // Distinguish client disconnect from upstream failure:
                    // If we can't write null packets to the client, the client is gone.
                    bool clientAlive = true;
                    try
                    {
                        var nullPkt = MpegTsHelper.CreateNullPacket();
                        await clientStream.WriteAsync(nullPkt, 0, nullPkt.Length, ct);
                        await clientStream.FlushAsync(ct);
                    }
                    catch
                    {
                        clientAlive = false;
                    }

                    if (!clientAlive)
                        throw; // re-throw so RouteAndHandleClient catches it as a clean disconnect

                    // Client is alive — this was an upstream failure
                    consecutiveFailures++;
                    int backoffMs = Math.Min(reconnectBaseMs * (1 << Math.Min(consecutiveFailures, 4)), 15000);

                    Logger.Log($"[StreamPipe] {clientId}: Upstream connection lost ({ex.Message}). Reconnecting in {backoffMs / 1000.0:F0}s... (attempt {consecutiveFailures}/{maxRetries})", Logger.LogLevel.Warning);

                    // Send more null packets to keep client decoder alive
                    try
                    {
                        var nullPkt = MpegTsHelper.CreateNullPacket();
                        for (int i = 0; i < 49; i++)
                            await clientStream.WriteAsync(nullPkt, 0, nullPkt.Length, ct);
                        await clientStream.FlushAsync(ct);
                    }
                    catch { break; }

                    if (consecutiveFailures >= maxRetries)
                    {
                        Logger.Log($"[StreamPipe] {clientId}: Too many consecutive upstream failures ({maxRetries}). Dropping client.", Logger.LogLevel.Error);
                        break;
                    }

                    await Task.Delay(backoffMs, ct);
                }
                catch (Exception ex) when (!ct.IsCancellationRequested)
                {
                    consecutiveFailures++;
                    int backoffMs = Math.Min(reconnectBaseMs * (1 << Math.Min(consecutiveFailures, 4)), 15000);

                    Logger.Log($"[StreamPipe] {clientId}: Upstream error ({ex.Message}). Reconnecting in {backoffMs / 1000.0:F0}s... (attempt {consecutiveFailures}/{maxRetries})", Logger.LogLevel.Warning);

                    try
                    {
                        var nullPkt = MpegTsHelper.CreateNullPacket();
                        for (int i = 0; i < 50; i++)
                            await clientStream.WriteAsync(nullPkt, 0, nullPkt.Length, ct);
                        await clientStream.FlushAsync(ct);
                    }
                    catch { break; }

                    if (consecutiveFailures >= maxRetries)
                    {
                        Logger.Log($"[StreamPipe] {clientId}: Too many consecutive upstream failures ({maxRetries}). Dropping client.", Logger.LogLevel.Error);
                        break;
                    }

                    await Task.Delay(backoffMs, ct);
                }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // Alert .ts splice
        // ────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Splices an alert .ts into the client stream at approximately real-time rate.
        /// The approach ("hard splice" / channel-change style):
        ///   1. Send a small burst of null packets with discontinuity indicators
        ///   2. Send the alert .ts **completely unmodified** — its own PAT/PMT
        ///      establishes a new program, exactly like a TV channel change.
        ///      No CC rewriting, no timestamp offsetting — this prevents the
        ///      HEVC PPS corruption that occurred when RewritePacket modified
        ///      PES header bytes in the video bitstream.
        ///   3. Data is paced at ~1.05× real-time to prevent TCP buffer overflow.
        ///   4. A trailing discontinuity burst signals the decoder that the
        ///      Tunarr stream (a second "channel change") is about to resume.
        /// This is the same approach used by real broadcast EAS systems (SCTE-35).
        /// </summary>
        /// <summary>
        /// Splices an alert .ts into the client stream.
        /// When a ChannelStreamProfile is available (matched mode), performs PID remapping
        /// at the TS header level and continues CC from the upstream's last values —
        /// making the alert appear as part of the same program (no channel change).
        /// When no profile is available, falls back to the original hard-splice approach.
        ///
        /// PID remapping is safe because only the 13-bit PID field in bytes 1-2 of
        /// each 188-byte TS packet header is modified. The compressed video/audio
        /// payload is never touched, avoiding the HEVC PPS corruption observed in
        /// earlier tests with RewritePacket (which modified PES headers).
        /// PAT and PMT tables are also rewritten — these are structured data, not
        /// compressed bitstream, so modification is safe.
        /// </summary>
        private async Task<(double ElapsedSeconds, string Diag)> SpliceAlertTs(
            string alertTsPath,
            Stream clientStream,
            string clientId,
            double alertDurationSeconds,
            CancellationToken ct,
            UpstreamPidMap? upstreamPidMap = null,
            ConcurrentDictionary<int, int>? ccTracker = null)
        {
            var spliceStopwatch = Stopwatch.StartNew();

            // ── Determine if we can do a matched (soft) splice ──
            // Learn the alert file's PID structure
            UpstreamPidMap? alertPidMap = null;
            Dictionary<int, int>? pidRemap = null;
            bool softSplice = false;

            if (upstreamPidMap?.IsLearned == true)
            {
                alertPidMap = LearnPidsFromFile(alertTsPath);
                if (alertPidMap?.IsLearned == true)
                {
                    pidRemap = BuildPidRemapTable(alertPidMap, upstreamPidMap);
                    softSplice = true;
                    Logger.Log($"[StreamPipe] {clientId}: Soft splice — PID remap: {string.Join(", ", pidRemap.Select(kv => $"0x{kv.Key:X}→0x{kv.Value:X}"))}", Logger.LogLevel.Debug);
                }
            }

            if (!softSplice)
            {
                // ── Hard splice fallback: send null gap with discontinuity ──
                var nullPkt = MpegTsHelper.CreateNullPacket();
                MpegTsHelper.SetDiscontinuityIndicator(nullPkt, 0);
                const int nullGapCount = 20;
                var nullBurst = new byte[MpegTsHelper.PacketSize * nullGapCount];
                for (int i = 0; i < nullGapCount; i++)
                    Buffer.BlockCopy(nullPkt, 0, nullBurst, i * MpegTsHelper.PacketSize, MpegTsHelper.PacketSize);

                await clientStream.WriteAsync(nullBurst, 0, nullBurst.Length, ct);
                await clientStream.FlushAsync(ct);
                Logger.Log($"[StreamPipe] {clientId}: Hard splice (unmatched) — sent discontinuity null gap", Logger.LogLevel.Debug);
            }

            // ── Read alert .ts and write paced ──
            var fileInfo = new FileInfo(alertTsPath);
            long totalFileBytes = fileInfo.Length;
            double safeDuration = Math.Max(alertDurationSeconds, 1.0);
            double targetBytesPerSecond = (totalFileBytes / safeDuration) * 1.05;

            using var fs = new FileStream(alertTsPath, FileMode.Open, FileAccess.Read, FileShare.Read, 65536);
            var buffer = new byte[MpegTsHelper.PacketSize * 1000];
            var paceClock = Stopwatch.StartNew();
            long totalBytesWritten = 0;
            bool firstChunk = true;

            string spliceMode = softSplice ? "PID-remapped soft splice" : "raw passthrough (hard splice)";
            Logger.Log($"[StreamPipe] {clientId}: Paced splice ({spliceMode}) — {totalFileBytes / 1024}KB over ~{safeDuration:F1}s at {targetBytesPerSecond / 1024:F0} KB/s", Logger.LogLevel.Debug);

            int bytesRead;
            while ((bytesRead = await fs.ReadAsync(buffer, 0, buffer.Length, ct)) > 0)
            {
                if (softSplice && pidRemap != null && pidRemap.Count > 0)
                {
                    // ── PID remap + CC continuation (TS header only — payload untouched) ──
                    int syncOff = MpegTsHelper.FindSyncOffset(buffer, 0, bytesRead);
                    if (syncOff >= 0)
                    {
                        int p = syncOff;
                        while (p + MpegTsHelper.PacketSize <= bytesRead)
                        {
                            if (buffer[p] != MpegTsHelper.SyncByte) { p += MpegTsHelper.PacketSize; continue; }

                            int origPid = MpegTsHelper.GetPid(buffer, p);

                            // Remap PID in the TS header (bytes 1-2 only)
                            if (pidRemap.TryGetValue(origPid, out int newPid))
                                MpegTsHelper.SetPid(buffer, p, newPid);

                            // Continue CC from upstream's last value for this PID
                            int effectivePid = pidRemap.TryGetValue(origPid, out int mapped) ? mapped : origPid;
                            if (MpegTsHelper.HasPayload(buffer, p) && ccTracker != null)
                            {
                                int nextCc = ccTracker.AddOrUpdate(effectivePid,
                                    _ => 0,
                                    (_, prev) => (prev + 1) & 0x0F);
                                MpegTsHelper.SetContinuityCounter(buffer, p, nextCc);
                            }

                            // Rewrite PAT: update PMT PID reference
                            if (origPid == MpegTsHelper.PidPat && MpegTsHelper.HasPayloadUnitStart(buffer, p))
                                RewritePatPmtPid(buffer, p, alertPidMap!.PmtPid, upstreamPidMap!.PmtPid);

                            // Rewrite PMT: update ES PIDs
                            if (origPid == alertPidMap!.PmtPid && MpegTsHelper.HasPayloadUnitStart(buffer, p))
                                RewritePmtEsPids(buffer, p, pidRemap);

                            p += MpegTsHelper.PacketSize;
                        }
                    }
                }
                else if (firstChunk && !softSplice)
                {
                    // ── Hard splice: set discontinuity on first packets ──
                    firstChunk = false;
                    int syncOff = MpegTsHelper.FindSyncOffset(buffer, 0, bytesRead);
                    if (syncOff >= 0)
                    {
                        int p = syncOff;
                        int marked = 0;
                        while (p + MpegTsHelper.PacketSize <= bytesRead && marked < 10)
                        {
                            if (buffer[p] == MpegTsHelper.SyncByte)
                            {
                                MpegTsHelper.SetDiscontinuityIndicator(buffer, p);
                                marked++;
                            }
                            p += MpegTsHelper.PacketSize;
                        }
                    }
                }

                await clientStream.WriteAsync(buffer, 0, bytesRead, ct);
                totalBytesWritten += bytesRead;

                // ── Pace control ──
                double expectedElapsed = totalBytesWritten / targetBytesPerSecond;
                double actualElapsed = paceClock.Elapsed.TotalSeconds;
                double aheadMs = (expectedElapsed - actualElapsed) * 1000.0;
                if (aheadMs > 20)
                {
                    await Task.Delay((int)aheadMs, ct);
                }
            }

            await clientStream.FlushAsync(ct);

            if (!softSplice)
            {
                // ── Hard splice: trailing discontinuity burst ──
                var trailNull = MpegTsHelper.CreateNullPacket();
                MpegTsHelper.SetDiscontinuityIndicator(trailNull, 0);
                var trailBurst = new byte[MpegTsHelper.PacketSize * 20];
                for (int i = 0; i < 20; i++)
                    Buffer.BlockCopy(trailNull, 0, trailBurst, i * MpegTsHelper.PacketSize, MpegTsHelper.PacketSize);
                await clientStream.WriteAsync(trailBurst, 0, trailBurst.Length, ct);
                await clientStream.FlushAsync(ct);
            }

            spliceStopwatch.Stop();
            string diag = $"{totalBytesWritten / 1024}KB written, {targetBytesPerSecond / 1024:F0} KB/s target, mode={spliceMode}";
            return (spliceStopwatch.Elapsed.TotalSeconds, diag);
        }

        /// <summary>
        /// Learns the PID structure from a .ts file on disk by parsing the first few KB.
        /// </summary>
        private static UpstreamPidMap? LearnPidsFromFile(string tsPath)
        {
            try
            {
                var pidMap = new UpstreamPidMap();
                var buffer = new byte[MpegTsHelper.PacketSize * 50]; // ~9KB — enough for PAT+PMT
                using var fs = new FileStream(tsPath, FileMode.Open, FileAccess.Read, FileShare.Read);
                int bytesRead = fs.Read(buffer, 0, buffer.Length);
                int syncOff = MpegTsHelper.FindSyncOffset(buffer, 0, bytesRead);
                if (syncOff < 0) return null;

                int pos = syncOff;
                while (pos + MpegTsHelper.PacketSize <= bytesRead)
                {
                    if (buffer[pos] == MpegTsHelper.SyncByte)
                        pidMap.LearnFromPacket(buffer, pos);
                    pos += MpegTsHelper.PacketSize;
                    if (pidMap.IsLearned) break;
                }
                return pidMap.IsLearned ? pidMap : null;
            }
            catch
            {
                return null;
            }
        }

        /// <summary>
        /// Rewrites the PMT PID reference inside a PAT table (in-place).
        /// Only modifies the structured PAT data, not compressed bitstream.
        /// </summary>
        private static void RewritePatPmtPid(byte[] packet, int offset, int oldPmtPid, int newPmtPid)
        {
            if (oldPmtPid == newPmtPid) return;

            int payOff = MpegTsHelper.GetPayloadOffset(packet, offset);
            if (payOff < 0) return;

            int pointer = packet[payOff];
            int tableStart = payOff + 1 + pointer;
            if (tableStart + 8 > offset + MpegTsHelper.PacketSize) return;
            if (packet[tableStart] != 0x00) return; // Not a PAT

            int sectionLength = ((packet[tableStart + 1] & 0x0F) << 8) | packet[tableStart + 2];
            int dataStart = tableStart + 8;
            int dataEnd = Math.Min(tableStart + 3 + sectionLength - 4, offset + MpegTsHelper.PacketSize);

            for (int i = dataStart; i + 3 < dataEnd; i += 4)
            {
                int programNum = (packet[i] << 8) | packet[i + 1];
                if (programNum == 0) continue; // NIT

                int pid = ((packet[i + 2] & 0x1F) << 8) | packet[i + 3];
                if (pid == oldPmtPid)
                {
                    packet[i + 2] = (byte)((packet[i + 2] & 0xE0) | ((newPmtPid >> 8) & 0x1F));
                    packet[i + 3] = (byte)(newPmtPid & 0xFF);
                }
            }
        }

        /// <summary>
        /// Rewrites elementary stream PID references inside a PMT table (in-place).
        /// Also rewrites the PCR PID. Only modifies structured PMT data.
        /// </summary>
        private static void RewritePmtEsPids(byte[] packet, int offset, Dictionary<int, int> pidRemap)
        {
            int payOff = MpegTsHelper.GetPayloadOffset(packet, offset);
            if (payOff < 0) return;

            int pointer = packet[payOff];
            int tableStart = payOff + 1 + pointer;
            if (tableStart + 12 > offset + MpegTsHelper.PacketSize) return;
            if (packet[tableStart] != 0x02) return; // Not a PMT

            int sectionLength = ((packet[tableStart + 1] & 0x0F) << 8) | packet[tableStart + 2];

            // Rewrite PCR PID
            int pcrPid = ((packet[tableStart + 8] & 0x1F) << 8) | packet[tableStart + 9];
            if (pidRemap.TryGetValue(pcrPid, out int newPcrPid))
            {
                packet[tableStart + 8] = (byte)((packet[tableStart + 8] & 0xE0) | ((newPcrPid >> 8) & 0x1F));
                packet[tableStart + 9] = (byte)(newPcrPid & 0xFF);
            }

            int programInfoLength = ((packet[tableStart + 10] & 0x0F) << 8) | packet[tableStart + 11];
            int esStart = tableStart + 12 + programInfoLength;
            int esEnd = Math.Min(tableStart + 3 + sectionLength - 4, offset + MpegTsHelper.PacketSize);

            int pos = esStart;
            while (pos + 5 <= esEnd)
            {
                int esPid = ((packet[pos + 1] & 0x1F) << 8) | packet[pos + 2];
                if (pidRemap.TryGetValue(esPid, out int newEsPid))
                {
                    packet[pos + 1] = (byte)((packet[pos + 1] & 0xE0) | ((newEsPid >> 8) & 0x1F));
                    packet[pos + 2] = (byte)(newEsPid & 0xFF);
                }
                int esInfoLength = ((packet[pos + 3] & 0x0F) << 8) | packet[pos + 4];
                pos += 5 + esInfoLength;
            }
        }

        /// <summary>
        /// Sends null TS packets (PID 0x1FFF) at approximately 3 Mbps for the specified
        /// duration. This keeps the TCP connection alive and prevents client read timeouts
        /// while the decoder plays through the buffered alert .ts at real-time PTS pace.
        ///
        /// Null packets are silently discarded by all MPEG-TS decoders — they exist
        /// precisely for bitrate padding. Sending them at the alert's muxrate ensures
        /// the client doesn't interpret a long silence as a stream failure.
        ///
        /// The drip sends ~2,000 packets/second in ~50ms bursts (100 packets per burst),
        /// yielding ~376 KB/s ≈ 3 Mbps — matching the alert .ts muxrate.
        /// </summary>
        private static async Task SendNullPacketDrip(
            Stream clientStream,
            double holdSeconds,
            string clientId,
            CancellationToken ct)
        {
            const int packetsPerBurst = 100;           // 100 × 188 = 18,800 bytes per burst
            const int burstIntervalMs = 50;            // 20 bursts/sec × 100 pkts = 2,000 pkts/sec ≈ 3 Mbps
            const double maxHoldSeconds = 120.0;       // safety cap — never hold longer than 2 minutes

            double cappedHold = Math.Min(holdSeconds, maxHoldSeconds);

            var nullPkt = MpegTsHelper.CreateNullPacket();
            var burstBuffer = new byte[MpegTsHelper.PacketSize * packetsPerBurst];
            for (int i = 0; i < packetsPerBurst; i++)
                Buffer.BlockCopy(nullPkt, 0, burstBuffer, i * MpegTsHelper.PacketSize, MpegTsHelper.PacketSize);

            var holdTimer = Stopwatch.StartNew();
            int burstCount = 0;

            Logger.Log($"[StreamPipe] {clientId}: Hold phase — sending null packet drip for {cappedHold:F1}s", Logger.LogLevel.Debug);

            try
            {
                while (!ct.IsCancellationRequested && holdTimer.Elapsed.TotalSeconds < cappedHold)
                {
                    await clientStream.WriteAsync(burstBuffer, 0, burstBuffer.Length, ct);
                    burstCount++;

                    // Adaptive delay: use remaining time if less than one interval
                    double remaining = cappedHold - holdTimer.Elapsed.TotalSeconds;
                    if (remaining <= 0) break;

                    int delayMs = (int)Math.Min(burstIntervalMs, remaining * 1000);
                    if (delayMs > 0)
                        await Task.Delay(delayMs, ct);
                }
            }
            catch (OperationCanceledException)
            {
                // Service shutting down — clean exit
            }

            holdTimer.Stop();
            Logger.Log($"[StreamPipe] {clientId}: Hold phase ended — {burstCount} bursts sent over {holdTimer.Elapsed.TotalSeconds:F1}s", Logger.LogLevel.Debug);
        }

        // ────────────────────────────────────────────────────────────────────
        // HLS proxy with alert injection
        // ────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Returns true if the HTTP request path is an HLS resource (.m3u8 playlist
        /// or a segment under an /hls/ path). These must NOT be piped as raw MPEG-TS.
        /// </summary>
        private static bool IsHlsPath(string path)
        {
            return path.EndsWith(".m3u8", StringComparison.OrdinalIgnoreCase)
                || path.Contains("/hls/", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Routes an HLS request: .m3u8 playlists are proxied with optional alert
        /// injection; all other HLS resources are proxied transparently to Tunarr.
        /// </summary>
        private async Task HandleHlsRequest(NetworkStream stream, string requestPath, CancellationToken ct)
        {
            if (requestPath.EndsWith(".m3u8", StringComparison.OrdinalIgnoreCase))
            {
                await ProxyHlsPlaylistWithInjection(stream, requestPath, ct);
                return;
            }

            // Regular HLS segment (.ts) — proxy transparently to Tunarr
            await ProxyApiRequestToTunarr(stream, requestPath, ct);
        }

        /// <summary>
        /// Fetches an HLS playlist from Tunarr and, if an alert is active, appends
        /// #EXT-X-DISCONTINUITY + alert segment entries before serving to the client.
        /// </summary>
        private async Task ProxyHlsPlaylistWithInjection(NetworkStream stream, string requestPath, CancellationToken ct)
        {
            try
            {
                string tunarrUrl = $"{_settings.TunarrBaseUrl.TrimEnd('/')}{requestPath}";

                using var response = await _apiProxyClient.GetAsync(tunarrUrl, ct);
                string content = await response.Content.ReadAsStringAsync(ct);

                // Check if alert injection is active and applicable
                string? injBlock = _alertHlsInjectionBlock;
                if (injBlock != null
                    && DateTime.UtcNow.Ticks < Interlocked.Read(ref _alertHlsExpiryTicks)
                    && !content.Contains(AlertHlsSegmentPrefix, StringComparison.OrdinalIgnoreCase))
                {
                    // Only inject if this channel has alerts enabled
                    bool inject = true;
                    var chMatch = Regex.Match(requestPath, @"/stream/channels/([^/.]+)", RegexOptions.IgnoreCase);
                    if (chMatch.Success)
                    {
                        var chState = ResolveChannel(chMatch.Groups[1].Value);
                        if (chState != null && !chState.Config.AlertInterruptEnabled)
                            inject = false;
                    }

                    if (inject)
                    {
                        content = InjectAlertIntoHlsPlaylist(content, injBlock);
                        Logger.Log($"[StreamPipe] HLS proxy: injected alert into {requestPath}", Logger.LogLevel.Debug);
                    }
                }

                byte[] body = Encoding.UTF8.GetBytes(content);

                var sb = new StringBuilder();
                sb.Append($"HTTP/1.1 {(int)response.StatusCode} {response.ReasonPhrase}\r\n");
                sb.Append("Content-Type: application/vnd.apple.mpegurl\r\n");
                sb.Append($"Content-Length: {body.Length}\r\n");
                sb.Append("Cache-Control: no-cache, no-store\r\n");
                sb.Append("Access-Control-Allow-Origin: *\r\n");
                sb.Append("Connection: close\r\n");
                sb.Append("\r\n");

                byte[] headerBytes = Encoding.ASCII.GetBytes(sb.ToString());
                await stream.WriteAsync(headerBytes, 0, headerBytes.Length, ct);
                await stream.WriteAsync(body, 0, body.Length, ct);
                await stream.FlushAsync(ct);
            }
            catch (Exception ex)
            {
                Logger.Log($"[StreamPipe] HLS playlist proxy error for {requestPath}: {ex.Message}", Logger.LogLevel.Warning);
                try
                {
                    string err = "HTTP/1.1 502 Bad Gateway\r\nConnection: close\r\nContent-Length: 0\r\n\r\n";
                    byte[] errBytes = Encoding.ASCII.GetBytes(err);
                    await stream.WriteAsync(errBytes, 0, errBytes.Length, ct);
                }
                catch { }
            }
        }

        /// <summary>
        /// Serves a pre-generated alert HLS segment (.ts) from the local temp directory.
        /// These segments are referenced by the injected playlist entries.
        /// </summary>
        private async Task ServeAlertHlsSegment(NetworkStream stream, string fileName, CancellationToken ct)
        {
            string? dir = _alertHlsDir;
            if (dir == null || !Directory.Exists(dir))
            {
                await SendHttpError(stream, 404, "Not Found", ct);
                return;
            }

            string filePath = Path.Combine(dir, fileName);
            if (!File.Exists(filePath))
            {
                await SendHttpError(stream, 404, "Not Found", ct);
                return;
            }

            try
            {
                byte[] body = await File.ReadAllBytesAsync(filePath, ct);

                var sb = new StringBuilder();
                sb.Append("HTTP/1.1 200 OK\r\n");
                sb.Append("Content-Type: video/mp2t\r\n");
                sb.Append($"Content-Length: {body.Length}\r\n");
                sb.Append("Cache-Control: no-cache\r\n");
                sb.Append("Access-Control-Allow-Origin: *\r\n");
                sb.Append("Connection: close\r\n");
                sb.Append("\r\n");

                byte[] headerBytes = Encoding.ASCII.GetBytes(sb.ToString());
                await stream.WriteAsync(headerBytes, 0, headerBytes.Length, ct);
                await stream.WriteAsync(body, 0, body.Length, ct);
                await stream.FlushAsync(ct);
            }
            catch (Exception ex)
            {
                Logger.Log($"[StreamPipe] Error serving alert segment {fileName}: {ex.Message}", Logger.LogLevel.Debug);
            }
        }

        /// <summary>
        /// Inserts the alert injection block into an HLS playlist, handling
        /// #EXT-X-ENDLIST positioning and newline hygiene.
        /// </summary>
        private static string InjectAlertIntoHlsPlaylist(string content, string injectionBlock)
        {
            bool hadEndList = false;
            string endListTag = "#EXT-X-ENDLIST";
            int endListIdx = content.LastIndexOf(endListTag, StringComparison.OrdinalIgnoreCase);
            if (endListIdx >= 0)
            {
                hadEndList = true;
                content = content.Substring(0, endListIdx).TrimEnd('\r', '\n');
            }

            if (content.Length > 0 && content[content.Length - 1] != '\n')
                content += "\n";

            var sb = new StringBuilder(content.Length + injectionBlock.Length + 32);
            sb.Append(content);
            sb.Append(injectionBlock);
            if (hadEndList)
                sb.AppendLine(endListTag);

            return sb.ToString();
        }

        /// <summary>
        /// Sends a simple HTTP error response and closes the connection.
        /// </summary>
        private static async Task SendHttpError(NetworkStream stream, int statusCode, string reason, CancellationToken ct)
        {
            try
            {
                string resp = $"HTTP/1.1 {statusCode} {reason}\r\nConnection: close\r\nContent-Length: 0\r\n\r\n";
                byte[] bytes = Encoding.ASCII.GetBytes(resp);
                await stream.WriteAsync(bytes, 0, bytes.Length, ct);
            }
            catch { }
        }

        // ────────────────────────────────────────────────────────────────────
        // HLS alert segment preparation (FFmpeg)
        // ────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Segments the alert .ts file into HLS-sized chunks using FFmpeg, stores them
        /// in a temp directory, and builds the injection block. Called in background
        /// when TriggerAlertSplice fires. After the alert duration + grace period,
        /// the temp directory is cleaned up automatically.
        /// </summary>
        private async Task PrepareAlertHlsSegmentsAsync(string tsPath, double durationSeconds)
        {
            try
            {
                // Clean up any previous alert segments
                CleanupAlertHlsDir();

                string tempDir = Path.Combine(Path.GetTempPath(), $"wsg_hls_pipe_{DateTime.UtcNow:yyyyMMddHHmmss}");
                Directory.CreateDirectory(tempDir);

                // Segment using FFmpeg (mux copy, no re-encode)
                string ffmpegPath = FFmpegLocator.GetFFmpegPath();
                if (!File.Exists(ffmpegPath)) ffmpegPath = "ffmpeg";

                string playlistPath = Path.Combine(tempDir, "eas_playlist.m3u8");
                string segmentPattern = Path.Combine(tempDir, $"{AlertHlsSegmentPrefix}%06d.ts");

                string args =
                    $"-y -i \"{tsPath}\" -c copy " +
                    $"-f hls -hls_time 4 " +
                    $"-hls_segment_filename \"{segmentPattern}\" " +
                    $"-hls_flags independent_segments " +
                    $"-hls_list_size 0 " +
                    $"\"{playlistPath}\"";

                Logger.Log($"[StreamPipe] HLS: segmenting alert {Path.GetFileName(tsPath)} into 4s chunks", Logger.LogLevel.Debug);

                var psi = new ProcessStartInfo
                {
                    FileName = ffmpegPath,
                    Arguments = args,
                    UseShellExecute = false,
                    CreateNoWindow = true,
                    RedirectStandardError = true,
                    RedirectStandardOutput = true
                };

                using var process = Process.Start(psi);
                if (process == null)
                {
                    Logger.Log("[StreamPipe] HLS: failed to start ffmpeg for segmentation.", Logger.LogLevel.Error);
                    return;
                }

                var stderrTask = process.StandardError.ReadToEndAsync();
                bool exited = await Task.Run(() => process.WaitForExit(60000));
                if (!exited)
                {
                    try { process.Kill(); } catch { }
                    Logger.Log("[StreamPipe] HLS: ffmpeg segmentation timed out (60s).", Logger.LogLevel.Error);
                    return;
                }

                if (process.ExitCode != 0)
                {
                    string stderr = await stderrTask;
                    Logger.Log($"[StreamPipe] HLS: ffmpeg segmentation failed (exit {process.ExitCode}): {stderr[..Math.Min(stderr.Length, 400)]}", Logger.LogLevel.Error);
                    return;
                }

                // Parse the generated playlist to get segment filenames and durations
                var segments = ParseHlsPlaylistFile(playlistPath, tempDir);
                if (segments.Count == 0)
                {
                    Logger.Log("[StreamPipe] HLS: ffmpeg produced no segments — HLS injection disabled for this alert.", Logger.LogLevel.Warning);
                    return;
                }

                // Build the injection block
                var sb = new StringBuilder();
                sb.AppendLine("#EXT-X-DISCONTINUITY");
                foreach (var (fileName, dur) in segments)
                {
                    sb.AppendLine($"#EXTINF:{dur.ToString("F6", CultureInfo.InvariantCulture)},");
                    sb.AppendLine(fileName);
                }
                sb.AppendLine("#EXT-X-DISCONTINUITY");

                // Publish — all fields set atomically from the caller's perspective
                // because each is a volatile write
                _alertHlsDir = tempDir;
                _alertHlsInjectionBlock = sb.ToString();
                Interlocked.Exchange(ref _alertHlsExpiryTicks, DateTime.UtcNow.AddSeconds(durationSeconds + 30).Ticks);

                Logger.Log($"[StreamPipe] ✓ HLS alert segments ready: {segments.Count} chunk(s) in {tempDir}", Logger.LogLevel.Info);

                // Schedule cleanup after expiry + grace period
                _ = Task.Run(async () =>
                {
                    await Task.Delay(TimeSpan.FromSeconds(durationSeconds + 90));
                    CleanupAlertHlsDir();
                });
            }
            catch (Exception ex)
            {
                Logger.Log($"[StreamPipe] HLS segment preparation failed: {ex.Message}", Logger.LogLevel.Warning);
            }
        }

        /// <summary>
        /// Parses a generated HLS playlist to extract segment filenames and durations.
        /// </summary>
        private static List<(string FileName, double Duration)> ParseHlsPlaylistFile(string playlistPath, string baseDir)
        {
            var result = new List<(string, double)>();
            if (!File.Exists(playlistPath)) return result;

            string[] lines = File.ReadAllLines(playlistPath);
            double nextDur = 0;

            for (int i = 0; i < lines.Length; i++)
            {
                string line = lines[i].Trim();
                if (line.StartsWith("#EXTINF:", StringComparison.OrdinalIgnoreCase))
                {
                    string durStr = line.Substring(8).TrimEnd(',');
                    double.TryParse(durStr, NumberStyles.Float, CultureInfo.InvariantCulture, out nextDur);
                }
                else if (!line.StartsWith("#") && !string.IsNullOrWhiteSpace(line) && nextDur > 0)
                {
                    string segPath = Path.Combine(baseDir, line);
                    if (File.Exists(segPath))
                        result.Add((line, nextDur));
                    nextDur = 0;
                }
            }

            return result;
        }

        /// <summary>
        /// Cleans up the temporary HLS alert segment directory and resets state.
        /// </summary>
        private void CleanupAlertHlsDir()
        {
            string? dir = _alertHlsDir;
            _alertHlsDir = null;
            _alertHlsInjectionBlock = null;
            Interlocked.Exchange(ref _alertHlsExpiryTicks, 0);

            if (dir != null)
            {
                try
                {
                    if (Directory.Exists(dir))
                        Directory.Delete(dir, true);
                    Logger.Log($"[StreamPipe] HLS: cleaned up alert segments in {dir}", Logger.LogLevel.Debug);
                }
                catch (Exception ex)
                {
                    Logger.Log($"[StreamPipe] HLS: cleanup failed for {dir}: {ex.Message}", Logger.LogLevel.Debug);
                }
            }
        }

        /// <summary>
        /// Builds a PID remap table: alert file PIDs → upstream (Tunarr) PIDs.
        /// Maps PMT PID, video PID(s), audio PID(s), and PCR PID.
        /// Currently unused but retained for future PID-remapping splice mode.
        /// </summary>
        private static Dictionary<int, int> BuildPidRemapTable(UpstreamPidMap alertPids, UpstreamPidMap upstreamPids)
        {
            var remap = new Dictionary<int, int>();

            // Don't remap if we haven't learned the upstream PIDs yet
            if (!upstreamPids.IsLearned) return remap;
            if (!alertPids.IsLearned) return remap;

            // Remap PMT PID
            if (alertPids.PmtPid > 0 && upstreamPids.PmtPid > 0 && alertPids.PmtPid != upstreamPids.PmtPid)
                remap[alertPids.PmtPid] = upstreamPids.PmtPid;

            // Remap video PID
            if (alertPids.VideoPid > 0 && upstreamPids.VideoPid > 0 && alertPids.VideoPid != upstreamPids.VideoPid)
                remap[alertPids.VideoPid] = upstreamPids.VideoPid;

            // Remap audio PID
            if (alertPids.AudioPid > 0 && upstreamPids.AudioPid > 0 && alertPids.AudioPid != upstreamPids.AudioPid)
                remap[alertPids.AudioPid] = upstreamPids.AudioPid;

            // Remap PCR PID (often same as video, but could be separate)
            if (alertPids.PcrPid > 0 && upstreamPids.PcrPid > 0 && alertPids.PcrPid != upstreamPids.PcrPid)
            {
                if (!remap.ContainsKey(alertPids.PcrPid))
                    remap[alertPids.PcrPid] = upstreamPids.PcrPid;
            }

            return remap;
        }

        /// <summary>
        /// Rewrites a single TS packet in-place: updates continuity counter for its PID
        /// and offsets any PTS/DTS/PCR timestamps.
        /// </summary>
        private static void RewritePacket(
            byte[] buffer,
            int offset,
            ConcurrentDictionary<int, int> ccTracker,
            long tickOffset)
        {
            int pid = MpegTsHelper.GetPid(buffer, offset);
            if (pid == MpegTsHelper.PidNull) return;

            // ── Continuity counter ──────────────────────────────────────
            if (MpegTsHelper.HasPayload(buffer, offset))
            {
                int nextCc = ccTracker.AddOrUpdate(pid,
                    _ => 0,
                    (_, prev) => (prev + 1) & 0x0F);
                MpegTsHelper.SetContinuityCounter(buffer, offset, nextCc);
            }

            // ── PCR offset ──────────────────────────────────────────────
            if (tickOffset != 0 && MpegTsHelper.HasPcr(buffer, offset))
            {
                long pcr = MpegTsHelper.GetPcrBase(buffer, offset);
                if (pcr >= 0)
                    MpegTsHelper.SetPcrBase(buffer, offset, pcr + tickOffset);
            }

            // ── PTS/DTS offset ──────────────────────────────────────────
            if (tickOffset != 0)
            {
                MpegTsHelper.OffsetTimestamps(buffer, offset, tickOffset);
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // Per-channel state
        // ────────────────────────────────────────────────────────────────────

        private class ChannelPipeState : IDisposable
        {
            public ProxyChannelConfig Config { get; }
            public int ListenPort { get; }
            private int _clientCount;
            public int ClientCount => _clientCount;

            public ChannelPipeState(ProxyChannelConfig config, int listenPort)
            {
                Config = config;
                ListenPort = listenPort;
            }

            public void IncrementClients() => Interlocked.Increment(ref _clientCount);
            public void DecrementClients() => Interlocked.Decrement(ref _clientCount);

            public void Dispose() { }
        }

        // ────────────────────────────────────────────────────────────────────
        // Upstream PID map — learned from PAT/PMT flowing through the pipe
        // ────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Tracks the PID structure of the upstream MPEG-TS by parsing PAT and PMT
        /// packets as they flow through the pipe. Used to remap alert .ts PIDs so
        /// they match the upstream's program structure, enabling clean splicing.
        /// </summary>
        private class UpstreamPidMap
        {
            public int PmtPid { get; private set; } = -1;
            public int PcrPid { get; private set; } = -1;
            public int VideoPid { get; private set; } = -1;
            public int AudioPid { get; private set; } = -1;

            /// <summary>True once we've successfully parsed both PAT and PMT.</summary>
            public bool IsLearned => PmtPid > 0 && (VideoPid > 0 || AudioPid > 0);

            private readonly HashSet<int> _pmtPids = new();

            /// <summary>
            /// Inspects a TS packet. If it's a PAT, learns the PMT PID(s).
            /// If it's a PMT, learns video/audio/PCR PIDs.
            /// </summary>
            public void LearnFromPacket(byte[] buffer, int offset)
            {
                int pid = MpegTsHelper.GetPid(buffer, offset);

                if (pid == MpegTsHelper.PidPat && MpegTsHelper.HasPayloadUnitStart(buffer, offset))
                {
                    var pmtPids = MpegTsHelper.ParsePatForPmtPids(buffer, offset);
                    if (pmtPids.Count > 0)
                    {
                        PmtPid = pmtPids[0]; // use first program's PMT
                        _pmtPids.Clear();
                        foreach (var p in pmtPids) _pmtPids.Add(p);
                    }
                }
                else if (_pmtPids.Contains(pid) && MpegTsHelper.HasPayloadUnitStart(buffer, offset))
                {
                    var (pcrPid, streams) = MpegTsHelper.ParsePmt(buffer, offset);
                    if (pcrPid >= 0) PcrPid = pcrPid;

                    foreach (var (streamType, esPid) in streams)
                    {
                        if (MpegTsHelper.IsVideoStreamType(streamType) && VideoPid < 0)
                            VideoPid = esPid;
                        else if (MpegTsHelper.IsAudioStreamType(streamType) && AudioPid < 0)
                            AudioPid = esPid;
                    }
                }
            }
        }
    }
}
