<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>BZTG</AssemblyName>
    <RootNamespace>BZTG</RootNamespace>
    <Title>Blitzortung Lightning API Wrapper</Title>
    <Product>Blitzortung Lightning API Wrapper</Product>
    <Company>NoID Softwork</Company>
    <Copyright>Copyright (c) NoID Softwork 2020-2026</Copyright>
    <Description>Library for accessing Blitzortung.org real-time lightning strike data for Canada and the Americas.</Description>
    <Version>1.1.6.0408</Version>
    <AssemblyVersion>1.1.6.0408</AssemblyVersion>
    <FileVersion>1.1.6.0408</FileVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WeatherShared\WeatherShared.csproj" />
  </ItemGroup>
</Project>